# =============================================================================
# - CAMINHOS DOS ARQUIVOS
# =============================================================================
Paths:
  # pastas
  out_dir: "output" # Diretório de saída para os arquivos processados.
  tmp_path: tmp     # Diretório de saída para os arquivos temporarios.
  # mapbiomas e shapefiles
  lulc_path: "inputs/mapbiomas_col10/mapbiomas_col10_{AREA}_{YEAR}.tif" # Caminho para o arquivo raster de uso e cobertura da terra (LULC)
  shp_path: "inputs/Shape_estados/{AREA}_Mapbiomas.shp" # Caminho para o arquivo shapefile do estado 
  shp_file: inputs/Shapes_ADAIMO_2025/ADAIMO_2025_{AREA}.shp # Caminho para o arquivo shapefile de area operacional (AOI)
  # script burn frequencia
  in_dir: "inputs/MODIS_BurnDate_RAW"                   # Diretório de entrada contendo os arquivos raster MODIS BurnDate_*.tif
  out_burn: "burn_frequency_para_{SYERAR}_{EYERAR}.tif" # Nome do arquivo raster de saida com a frequencia das queimadas.
  raster_modis: "BurnDate_*.tif"                        # Nome do arquivo raster MODIS (padrão: BurnDate_*.tif)
  # script condicoes de queimadas
  out_reproj: "tmp/burn_reproj_temp.tif"                # Caminho para o arquivo raster reprojetado (temporário)
  out_cond_burn: "map_cond_burn_{AREA}_{YEAR}.tif"      # Caminho para o arquivo raster de condição de queimadas (Estado)
  out_clip_burn: "map_cond_burn_{AREA}_{YEAR}_clip.tif" # Caminho para o arquivo raster de condição de queimadas recortado pelo shapefile (AIO) -- Desativado no script
  tabela_csv: "inputs/Planilhas/tabela_queimadas.csv"      # Caminho para o arquivo CSV contendo a tabela de classes de condição de queimadas 
  # script condicoes de borda
  out_cond_edge: "map_cond_edge_{AREA}_{YEAR}.tif"      # Caminho para o arquivo raster de condição de borda (Estado)
  out_clip_edge: "map_cond_edge_{AREA}_{YEAR}_clip.tif" # Caminho para o arquivo raster de condição de borda recortado pelo shapefile (AIO) -- Desativado no script
  mask_temp: "tmp/temp_shape_mask.tif"                  # Caminho para o arquivo raster temporário de máscara do shapefile (temporário)
  # script condicoes de vegetacao segundaria
  sec_veg_map_file: "inputs/Flor_Sec_col10/raster_Sec_Veg_col10_{AREA}_{YEAR}.tif"  # Caminho para o arquivo raster da vegetação segundaria
  sec_veg_weight_map_file: "output/veg_sec_weight_{AREA}_{YEAR}.tif"                # Caminho para o arquivo raster de condição da vegetação segundaria (AIO)
  # script de condicoes do ecossistema
  fito_map_file: "inputs/Fitofisionomia/Brasil_vege_areaWGS84.shp" # Caminho para o arquivo shapefile das fitofisionomias 
  # script de comparacao de condicoes
  bioma_map_file: "inputs_indicadores/inputs/Biomas/{BIOMA}.shp"      # Caminho para o shape de biomas
  condition_map_file_base: output/map_weights_100_{BASE_YEAR}.tif     # Caminho para o mapa de condicao ano base
  condition_map_file_end: output/map_weights_100_{END_YEAR}.tif       # Caminho para o mapa de condicao ano final
  area_map_file: "inputs/Mapa_Area/pxA_x10m2_sembuffer.tif"           # Caminho para o mapa de area
  opunit_id_csv_file: "inputs/Planilhas/OpUnit_ID_2025.csv"             # Arquivo csv contendo os IDs de cada unidade operacional
  opunit_id_map_file: "inputs/Mapas_OpUnit_2025/ADAimo_{AREA}_2025.tif" # Diretorio do mapa de IDs de cada unidade operacional
  opunit_metadata_file: "inputs/Planilhas/OpUnit_Lista_2025.csv"        # Arquivo csv contendo os metadados de cada unidade operacional
  legendas_file: "inputs/Planilhas/Dicionario.xlsx"                     # Arquivo xlsx com as legendas de LULC, Fitofisionomia, Queimadas Pixels de Borda
  # script de GRI_106_107
  file_table_comparison: "output/lulc_condicao_legenda_{AREA}.xlsx"
  file_reclass_path: "inputs/Planilhas/Reclass_{AREA}.xlsx"
  output_g106: "output/Saida1016_{AREA}.csv"
  output_g107: "output/Saida1017b_{AREA}.csv"
  output_lulc_cond: "output/lulc_condicao_reclass_{AREA}.csv"
  output_balance: "output/Saida_balanco_natural_{AREA}.csv"


# =============================================================================
# - VARIÁVEIS
# =============================================================================
Data:
  # Variaveis globais
  area: "PA"       # Estado de interesse - Ex: PA
  start_year: 2000 # Ano inicial para o cálculo da frequência de queimadas
  end_year: 2024   # Ano final para o processamento, usado em todos os scripts
  base_year_veg: 1985  # Ano base usado no script de vegetacao segundaria.
  base_year_compare: 2020 # Ano final para o processamento, usado em comparacao de condicoes
  # Variaveis usadas pelos script burn frq, queimadas e bordas
  max_ram_usage: 0.6  # Porcentagem máxima de uso de RAM (0.6 = 60%)
  nodata: -9999       # Nodata (Alterado para valores negativo). NÃO USAR ZERO AQUI - Condicao de borda apresenta valores negativos no raster.
  byte_pixel: 50      # Tamanho do pixel em bytes (usado para estimar o uso de RAM)
  blocksize: 256      # Tamanho do bloco
  tile_size_min: 4096 # Pixels por lado de cada tile (usado para otimizar o processamento em tiles)
  compresssion: "lzw" # Tipo de compressão para os arquivos de saída (usado nos scripts de queimadas e borda)
  tiled: true         # Se True, os arquivos de saída serão salvos em formato tiled (usado nos scripts de queimadas e borda)
  all_touched: true   # Se True, considera todos os pixels tocados pelo polígono; se False, apenas os pixels cujo centro está dentro do polígono (Variavel usada nos 3 scripts citados).
  # Variaveis usadas pelo script burn frq
  tolerance: 0.0001     # Tolerância para simplificação da geometria do shapefile (em graus)
  crs_corr: "EPSG:4326" # Sistema de referência de coordenadas (CRS)
  # Variaveis usadas pelo script borda
  classes_naturais: [0, 3, 4, 5, 6, 11, 12, 23, 29, 32, 33] # Classes de uso e cobertura da terra (LULC) consideradas naturais (sem efeito de borda), ZERO - area classificadas sem dados pelo Mapbiomas
  overlap: 100          # Sobreposição em pixels para o recorte do shapefile (usado para evitar bordas vazias)
  cond_borda: 30        # Condicao de borda inicial (para cálculo da condição)
  size_pixel: 30        # Tamanho do pixel em metros (para cálculo da condição)
  dist_max_pixel: 100   # Valor máximo da condição de borda (para cálculo da condição)
  dist_max_metros: 1000 # Distância máxima do efeito de borda em metros (para cálculo da condição)
  funcao: "linear"      # "linear"  ou "exponencial" ---  VERSAO BETA (EXPONENCIAL) - não troque
  # Variaveis usadas pelo script vegetação segundaria
  id_class_veg: 3         # Id da classe vegetal
  all_touched_veg: false  # Opção all_touched do rasterio para script de vegetação segundaria
  # Variaveis usadas pelo script condicao dos ecossistemas
  id_class_cond: [3, 6]   # Classes selecionadas
  all_touched_cond: false # Opção all_touched do rasterio para script de condicao dos ecossistemas
  nodata_cond: 0          # Nodata - após a algebra de raster que modifica os valores de pixel, pode ser usar o valor Zero para pixel sem dados.
  # script de comparacao de condicoes
  n_condition_classes: 5     # numero de classes de condicao
  id_class_compare: 3        # Classes selecionadas
  all_touched_compare: false # Opção all_touched do rasterio para script de comparacao de condicoes
  # script de GRI_106_107
  decimal_separator: "," # Separador decimal para os arquivos CSV de saída ("," ou ".")
  separator: ";"         # Separador de campo para os arquivos CSV de saída (";" ou ",")
  float_format: "%.5f"   # Formato de ponto flutuante para os arquivos CSV de saída (ex: "%.2f" para duas casas decimais)
