# ─────────────────────────────────────────────────────────────────────────────
# Pipeline Sequencial: Veg_sec -> Down -> Burn -> Queimadas -> Borda
# ─────────────────────────────────────────────────────────────────────────────


services:

  npi_tables:
    build:
      context: .
      dockerfile: Dockerfile
    image: npi-geo:latest
    container_name: npi_tables
    volumes:
      - ./:/app:delegated
    working_dir: /app
    #environment:
    #  - PYTHONUNBUFFERED=1
    command: ["python3", "compare_maps_condicao.py"]
    restart: "no"

  npi_GRI:
    image: npi-geo:latest
    container_name: npi_GRI
    volumes:
      - ./:/app:delegated
    working_dir: /app
    #environment:
    #  - PYTHONUNBUFFERED=1
    command: ["python3", "GRI_UPDATE.py"]
    restart: "no"
    depends_on:
      npi_tables:
        condition: service_completed_successfully